create endpoint for /api/articles/article_id #14
MrChris-H/News pull request #4
Opened 2022-02-14 16:13 UTC by MrChris-H

2022-02-14 16:48 UTC, maddierosecodes approved these changes
Looking good.

I don't think the index.js to switch between data types is necessary. You can just require the test data directly into the test suite, this is more efficient as the index.js is performing additional conditional checks :)

2022-02-15 11:04 UTC, MrChris-H commented
one of those commits removed the index as requested before

2022-02-15 11:33 UTC, emilyb93 requested changes

2022-02-15 11:33 UTC, emilyb93 commented on __tests__/app.test.js
> +      it('Status 400, msg: "article does not exist"', () => {
I would say this for this instance, a 404 would be better as the request is fine, but the article number doesn't exist yet but could do in future. 400 Bad Request is more reserved for bad data type input

2022-02-15 11:33 UTC, emilyb93 commented on controllers/article-controllers.js
> +
I would remove this patch request function from this branch and keep each branch as a method and endpoint, as opposed to a branch for an endpoint and all its associated methods.

2022-02-15 11:33 UTC, emilyb93 commented on controllers/custom-error-controller.js
> +  if (err.status === 400 && err.msg === "article does not exist") {
Again, a 404 would be better for this error as 400 implies Bad Request === bad data input/wrong data type

2022-02-15 11:33 UTC, emilyb93 commented on models/articles-models.js
> +    .query("SELECT * FROM articles WHERE article_id = $1", [id])
Close your psql strings with a ;

2022-02-15 11:33 UTC, emilyb93 commented on models/topics-models.js
> +  return db.query("SELECT * FROM topics").then(({ rows }) => {
Close your psql strings with a ;

2022-02-15 12:17 UTC, merged